### ISSUE TITLE
README 和许可协议问题

### ISSUE THREAD

**Issue by jyhi** [iamapig120/SimPad_firmware_8051#7]
在 #6 中我注意到 [README.md](README.md) 中的一些问题：

1. “文件说明”一节的表格后两行（Markdown 第 22、23 行）似乎是重复的描述。
2. “参与编辑”一节中提到“您编写的固件”或许是一种不恰当的描述；这句话应是在表述“SimPad 将持续推送（带有您的贡献的）固件至全球用户”。

另，“请注意”一节中对 SimPad 固件和设计资料的用途作出了进一步的限制。~~我尚未深入调查，但~~您在本仓库设置的 GNU AGPL v3.0 许可证[~~应该~~不允许这类附加条件的行为](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary)（或者说是无效的）：在 GNU AGPL v3 和 GNU GPL v3 的 [7. Additional Terms.](https://www.gnu.org/licenses/gpl-3.0.html#section7)（[七、附加条款](https://jxself.org/translations/gpl-3.zh.shtml)）中，协议文本指出“如果你接收到的程序或其部分，声称受本协议约束，却补充了这种进一步的限制条款，你可以去掉它们。”但是，你**可以利用**前述条款中的例外 b) c) d) e) 来进一步约束第三方对 SimDevices 和 SimPad 商标或名誉的使用。另 GNU AGPL 虽然作为自由软件阵营中限制最多的许可证，其相比 GNU GPL 多出的限制却是针对服务端软件的（例如，SaaS），因此或许您应该使用 GNU GPL v3 来作为 SimPad 固件源代码和设计文件的许可证。

**Comment by iamapig120** [comment]
是的，这方面确实存在一些问题需要修正，感谢您的指正！
附加条件之后应该会被移除以确保对AGPL及GPL的合规，并修改协议至GPL
十分感谢您的意见！

**Comment by iamapig120** [comment]
因为 AGPL 协议某种程度上算GPL的超集，所以仍保留了AGPL协议
并从 SDCC 分支同步了新版本测试中的固件到 master 分支
英文版 README 尚未更新翻译
